
export interface Location {
  id: string;
  name: string;
  coordinates: {
    latitude: number;
    longitude: number;
  };
}

export interface JeepneyRoute {
  name: string;
  description: string;
  color?: string;
}

export interface RouteSegment {
  id?: string; // Optional because it's generated by Firestore
  source: string; // location id
  target: string; // location id
  distance: number; // distance in km
  routeName: string; // jeepney route name
  stopAndTransfer?: string;
}

export interface Graph {
  nodes: Location[];
  edges: RouteSegment[];
  routes: JeepneyRoute[];
}

export interface PathSegment {
  from: string;
  to: string;
  routeName: string;
  distance: number;
  vehicleType?: string;
  regularFare?: number;
  discountedFare?: number;
  pathCoordinates?: [number, number][] | null;
}

export interface ShortestPathResult {
  path: PathSegment[];
  totalDistance: number;
  totalFare?: number;
  discountedFare?: number;
  rideCount?: number;
  alternatives?: ShortestPathResult[];
  rawDijkstraPath?: {
    path: PathSegment[];
    totalDistance: number;
    totalFare: number;
    discountedFare: number;
    rideCount: number;
    alternatives?: ShortestPathResult[] | null;
  } | null;
}
