import { GeoPoint } from "firebase/firestore";

export interface Location {
  id: string;
  name: string;
  coordinates: {
    latitude: number;
    longitude: number;
  };
}

export interface JeepneyRoute {
  name: string;
  description: string;
}

export interface RouteSegment {
  id?: string; // Optional because it's generated by Firestore
  source: string; // location id
  target: string; // location id
  distance: number; // distance in km
  routeName: string; // jeepney route name
}

export interface Graph {
  nodes: Location[];
  edges: RouteSegment[];
  routes: JeepneyRoute[];
}

export interface PathSegment {
  from: string;
  to: string;
  routeName: string;
  distance: number;
  regularFare?: number;
  discountedFare?: number;
}

export interface ShortestPathResult {
  path: PathSegment[];
  totalDistance: number;
  totalFare?: number;
  discountedFare?: number;
}
